### ISSUE TITLE
if an alignment on a variation part of gedmap 

### ISSUE THREAD

**Issue by hphphpcat** [th0mas-buechler/gedmap#6]
if an alignment  hit on a variation part of gedmap , the question is   how can we convert this alignment to the linear reference position just use the bit-vector data-structure to count the number of characters on reference？

**Comment by thomas-buechler-ulm** [comment]
If a reported alignment starts at a variation part, then:
- there is no well defined position in the reference genome for this alignment

What the program does (when using the -2fa option):
- the reported position is the nearest reference position before the variation and 
- there will be the optional field XO:i:x in the sam line, with x being the offset from the last position.

Example: With **ref=AATCGAAT** and the variation **CG->GGC** it is **EDS=AAT(CG|GGC)AAT**; pattern **P=GCAAT** can be found exactly at position **9** in the **EDS**. But this is in the variant part, which has no correspondence in **ref**. The nearest (to the left) position in the **EDS**, that has a correspondence in **ref** is 'G' at position **6 in the EDS** and at position **5 in ref**. In the sam file fild 4 (POS) will therefore be **5** and there will be the optional field **XO:i:3** (, because 9-6=3). (Without using -2fa the reported POS will simply be 9.)

**Comment by hphphpcat** [comment]
ok thank U!!!!!
